runtime: python314
automatic_scaling:
  max_instances: 1

handlers:
  - url: /
    static_files: site/index.html
    upload: site/index\.html

  - url: /nl
    static_files: site/index-nl.html
    upload: site/index-nl\.html

  - url: /about
    static_files: site/about.html
    upload: site/about\.html

  - url: /over
    static_files: site/over.html
    upload: site/over\.html

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: site/static/images/favicon\.ico

  - url: /static/css
    static_dir: site/static/css

  - url: /static/images
    static_dir: site/static/images

  - url: /static/js
    static_dir: site/static/js

  - url: /static/fonts
    static_dir: site/static/fonts

  - url: /people
    static_dir: site/people

  - url: /people
    static_dir: site/people

  - url: /mensen
    static_dir: site/mensen

  - url: /.*
    script: auto
